// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/shopspring/decimal"
)

type Item struct {
	ID          int32
	OrderID     string
	ChrtID      int32
	TrackNumber string
	Price       decimal.Decimal
	Rid         string
	Name        string
	Sale        decimal.Decimal
	Size        string
	TotalPrice  decimal.Decimal
	NmID        int32
	Brand       string
	Status      int32
}

type Order struct {
	ID                string
	TrackNumber       string
	Entry             string
	Locale            string
	InternalSignature string
	CustomerID        string
	DeliveryService   string
	Shardkey          string
	SmID              int32
	DateCreated       time.Time
	OofShard          string
	DeliveryName      string
	DeliveryCity      string
	DeliveryPhone     string
	DeliveryZip       string
	DeliveryAddress   string
	DeliveryRegion    string
	DeliveryEmail     string
}

type Payment struct {
	Transaction  string
	OrderID      string
	RequestID    string
	Currency     string
	Provider     string
	Amount       decimal.Decimal
	PaymentDt    int64
	Bank         string
	DeliveryCost decimal.Decimal
	GoodsTotal   int32
	CustomFee    decimal.Decimal
}
