// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    track_number,
    entry,
    locale,
    internal_signature,
    customer_id,
    delivery_service,
    shardkey,
    sm_id,
    date_created,
    oof_shard,
    delivery_name,
    delivery_phone,
    delivery_zip,
    delivery_address,
    delivery_region,
    delivery_email,
    delivery_city
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, track_number, entry, locale, internal_signature, customer_id, delivery_service, shardkey, sm_id, date_created, oof_shard, delivery_name, delivery_city, delivery_phone, delivery_zip, delivery_address, delivery_region, delivery_email
`

type CreateOrderParams struct {
	ID                string
	TrackNumber       string
	Entry             string
	Locale            string
	InternalSignature string
	CustomerID        string
	DeliveryService   string
	Shardkey          string
	SmID              int32
	DateCreated       time.Time
	OofShard          string
	DeliveryName      string
	DeliveryPhone     string
	DeliveryZip       string
	DeliveryAddress   string
	DeliveryRegion    string
	DeliveryEmail     string
	DeliveryCity      string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.TrackNumber,
		arg.Entry,
		arg.Locale,
		arg.InternalSignature,
		arg.CustomerID,
		arg.DeliveryService,
		arg.Shardkey,
		arg.SmID,
		arg.DateCreated,
		arg.OofShard,
		arg.DeliveryName,
		arg.DeliveryPhone,
		arg.DeliveryZip,
		arg.DeliveryAddress,
		arg.DeliveryRegion,
		arg.DeliveryEmail,
		arg.DeliveryCity,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TrackNumber,
		&i.Entry,
		&i.Locale,
		&i.InternalSignature,
		&i.CustomerID,
		&i.DeliveryService,
		&i.Shardkey,
		&i.SmID,
		&i.DateCreated,
		&i.OofShard,
		&i.DeliveryName,
		&i.DeliveryCity,
		&i.DeliveryPhone,
		&i.DeliveryZip,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryEmail,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, track_number, entry, locale, internal_signature, customer_id, delivery_service, shardkey, sm_id, date_created, oof_shard, delivery_name, delivery_city, delivery_phone, delivery_zip, delivery_address, delivery_region, delivery_email
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TrackNumber,
		&i.Entry,
		&i.Locale,
		&i.InternalSignature,
		&i.CustomerID,
		&i.DeliveryService,
		&i.Shardkey,
		&i.SmID,
		&i.DateCreated,
		&i.OofShard,
		&i.DeliveryName,
		&i.DeliveryCity,
		&i.DeliveryPhone,
		&i.DeliveryZip,
		&i.DeliveryAddress,
		&i.DeliveryRegion,
		&i.DeliveryEmail,
	)
	return i, err
}

const getRecentOrders = `-- name: GetRecentOrders :many
SELECT id, track_number, entry, locale, internal_signature, customer_id, delivery_service, shardkey, sm_id, date_created, oof_shard, delivery_name, delivery_city, delivery_phone, delivery_zip, delivery_address, delivery_region, delivery_email
FROM orders
ORDER BY date_created DESC
LIMIT $1
`

func (q *Queries) GetRecentOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, getRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TrackNumber,
			&i.Entry,
			&i.Locale,
			&i.InternalSignature,
			&i.CustomerID,
			&i.DeliveryService,
			&i.Shardkey,
			&i.SmID,
			&i.DateCreated,
			&i.OofShard,
			&i.DeliveryName,
			&i.DeliveryCity,
			&i.DeliveryPhone,
			&i.DeliveryZip,
			&i.DeliveryAddress,
			&i.DeliveryRegion,
			&i.DeliveryEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
