cache:
  prefill:
    enabled: true
    timeout: 3s
  size: 1000
log:
  level: debug
postgres:
  conn_string: postgres://postgres:development@db:5432/postgres
kafka_consumer:
  servers: broker:29092
  group_id: 1
  topic: orders
  read_timeout: 1s
  read_failure_backoff: 3s
  process_timeout: 300ms
api:
  host: 0.0.0.0
  port: 80
  timeout: 1s
